@ChatServer_HostAddress = http://192.168.20.17:5201

### LOGIN
POST {{ChatServer_HostAddress}}/login
Content-Type: application/json

{
    "username": "Ducklord",
    "password": "chatking"
}

### REGISTER
POST {{ChatServer_HostAddress}}/register
Content-Type: application/json

{
    "username": "CoolUser2",
    "password": "pass"
}

### GET ALL USERS
# Returns a JSON array of all registered usernames
GET {{ChatServer_HostAddress}}/users

### SEND MESSAGE
POST {{ChatServer_HostAddress}}/send-message
Content-Type: application/json

{
    "sender": "Ducklord",
    "content": "Hello from Ducklord"
}

### GET ALL MESSAGES
# Returns a JSON list containing every stored chat message (in insertion order)
GET {{ChatServer_HostAddress}}/messages/history

