@ChatServer_HostAddress = http://localhost:5201

POST http://localhost:5201/login
Content-Type: application/json

{
    "username": "Ducklord",
    "password": "chatking"
}

###

POST http://localhost:5201/register
Content-Type: application/json

{
    "username": "CoolUser2",
    "password": "pass"
}

###

GET http://localhost:5201/users
Content-Type: application/json


